var searchData=
[
  ['data_11652',['data',['http://www.dealii.org/developer/doxygen/deal.II/structboost_1_1geometry_1_1traits_1_1access_3_1_1Point_3_01dim_00_01Number_01_4_00_01D_01_4.html',1,'data&lt; D, dim, class &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/structCUDAWrappers_1_1MatrixFree_1_1Data.html',1,'CUDAWrappers::MatrixFree::Data']]],
  ['dataentrybase_11653',['DataEntryBase',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DataOutImplementation_1_1DataEntryBase.html',1,'internal::DataOutImplementation']]],
  ['datahost_11654',['DataHost',['http://www.dealii.org/developer/doxygen/deal.II/structCUDAWrappers_1_1DataHost.html',1,'CUDAWrappers']]],
  ['dataout_11655',['DataOut',['../class_parsed_tools_1_1_data_out.html',1,'ParsedTools::DataOut&lt; dim, spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'DataOut&lt; dim, spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classParticles_1_1DataOut.html',1,'Particles::DataOut&lt; dim, spacedim &gt;']]],
  ['dataout_3c_20dim_20_3e_11656',['DataOut&lt; dim &gt;',['../class_parsed_tools_1_1_data_out.html',1,'ParsedTools::DataOut&lt; dim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'DataOut&lt; dim &gt;']]],
  ['dataout_3c_20dim_2c_20dim_20_3e_11657',['DataOut&lt; dim, dim &gt;',['../class_parsed_tools_1_1_data_out.html',1,'ParsedTools']]],
  ['dataout_3c_20patch_5fdim_2c_20spacedim_20_3e_11658',['DataOut&lt; patch_dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'']]],
  ['dataout_5fdofdata_11659',['DataOut_DoFData',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_20_2d_201_2c_20spacedim_2c_20spacedim_20_3e_11660',['DataOut_DoFData&lt; dim, dim - 1, spacedim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_2b1_2c_20spacedim_2c_20spacedim_2b1_20_3e_11661',['DataOut_DoFData&lt; dim, dim+1, spacedim, spacedim+1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_2c_20dim_2c_20dim_20_3e_11662',['DataOut_DoFData&lt; dim, dim, dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_2c_20spacedim_2c_20spacedim_20_3e_11663',['DataOut_DoFData&lt; dim, dim, spacedim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20patch_5fdim_2c_20spacedim_2c_20spacedim_20_3e_11664',['DataOut_DoFData&lt; dim, patch_dim, spacedim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataoutfaces_11665',['DataOutFaces',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutFaces.html',1,'']]],
  ['dataoutfilter_11666',['DataOutFilter',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutBase_1_1DataOutFilter.html',1,'DataOutBase']]],
  ['dataoutfilterflags_11667',['DataOutFilterFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1DataOutFilterFlags.html',1,'DataOutBase']]],
  ['dataoutinterface_11668',['DataOutInterface',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_200_2c_20spacedim_20_3e_11669',['DataOutInterface&lt; 0, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_202_2c_202_20_3e_11670',['DataOutInterface&lt; 2, 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2b1_2c_20spacedim_2b1_20_3e_11671',['DataOutInterface&lt; dim+1, spacedim+1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2c_20dim_20_3e_11672',['DataOutInterface&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20patch_5fdim_2c_20patch_5fspacedim_20_3e_11673',['DataOutInterface&lt; patch_dim, patch_spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutreader_11674',['DataOutReader',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutReader.html',1,'']]],
  ['dataoutresample_11675',['DataOutResample',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutResample.html',1,'']]],
  ['dataoutrotation_11676',['DataOutRotation',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutRotation.html',1,'']]],
  ['dataoutstack_11677',['DataOutStack',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutStack.html',1,'']]],
  ['dataoutstack_3c_20dim_2c_20spacedim_2c_20void_20_3e_11678',['DataOutStack&lt; dim, spacedim, void &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutStack_3_01dim_00_01spacedim_00_01void_01_4.html',1,'']]],
  ['datapostprocessor_11679',['DataPostprocessor',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessor.html',1,'']]],
  ['datapostprocessor_3c_20spacedim_20_3e_11680',['DataPostprocessor&lt; spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessor.html',1,'']]],
  ['datapostprocessorscalar_11681',['DataPostprocessorScalar',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorScalar.html',1,'']]],
  ['datapostprocessortensor_11682',['DataPostprocessorTensor',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorTensor.html',1,'']]],
  ['datapostprocessorvector_11683',['DataPostprocessorVector',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorVector.html',1,'']]],
  ['dataset_11684',['DataSet',['http://www.dealii.org/developer/doxygen/deal.II/classHDF5_1_1DataSet.html',1,'HDF5']]],
  ['datasetdescriptor_11685',['DataSetDescriptor',['http://www.dealii.org/developer/doxygen/deal.II/classQProjector_1_1DataSetDescriptor.html',1,'QProjector']]],
  ['datatransfer_11686',['DataTransfer',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase_1_1DataTransfer.html',1,'parallel::DistributedTriangulationBase']]],
  ['datavector_11687',['DataVector',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutStack_3_01dim_00_01spacedim_00_01void_01_4_1_1DataVector.html',1,'DataOutStack&lt; dim, spacedim, void &gt;']]],
  ['deal_5fii_5fintermediateflags_11688',['Deal_II_IntermediateFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1Deal__II__IntermediateFlags.html',1,'DataOutBase']]],
  ['defaulthierarchy_11689',['DefaultHierarchy',['http://www.dealii.org/developer/doxygen/deal.II/structhp_1_1FECollection_1_1DefaultHierarchy.html',1,'hp::FECollection']]],
  ['defaultpolicy_11690',['DefaultPolicy',['http://www.dealii.org/developer/doxygen/deal.II/classRepartitioningPolicyTools_1_1DefaultPolicy.html',1,'RepartitioningPolicyTools']]],
  ['deleter_11691',['Deleter',['http://www.dealii.org/developer/doxygen/deal.II/classAlignedVector_1_1Deleter.html',1,'AlignedVector']]],
  ['deleteractionbase_11692',['DeleterActionBase',['http://www.dealii.org/developer/doxygen/deal.II/classAlignedVector_1_1Deleter_1_1DeleterActionBase.html',1,'AlignedVector::Deleter']]],
  ['derivativeform_11693',['DerivativeForm',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20dim_2c_20spacedim_20_3e_11694',['DerivativeForm&lt; 1, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20spacedim_2c_20dim_20_3e_11695',['DerivativeForm&lt; 1, spacedim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_202_2c_20dim_2c_20spacedim_20_3e_11696',['DerivativeForm&lt; 2, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_203_2c_20dim_2c_20spacedim_20_3e_11697',['DerivativeForm&lt; 3, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_204_2c_20dim_2c_20spacedim_20_3e_11698',['DerivativeForm&lt; 4, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeselector_11699',['DerivativeSelector',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_201_2c_20dim_20_3e_11700',['DerivativeSelector&lt; 1, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_011_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_202_2c_20dim_20_3e_11701',['DerivativeSelector&lt; 2, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_012_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_203_2c_20dim_20_3e_11702',['DerivativeSelector&lt; 3, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_013_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['description_11703',['Description',['http://www.dealii.org/developer/doxygen/deal.II/structTriangulationDescription_1_1Description.html',1,'TriangulationDescription']]],
  ['detector_11704',['detector',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SupportsOperation_1_1detector.html',1,'internal::SupportsOperation']]],
  ['detector_3c_20default_2c_20void_5ft_3c_20op_3c_20args_2e_2e_2e_20_3e_20_3e_2c_20op_2c_20args_2e_2e_2e_20_3e_11705',['detector&lt; Default, void_t&lt; Op&lt; Args... &gt; &gt;, Op, Args... &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SupportsOperation_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_0f78ab3014b3a6806d036c3d96444b509.html',1,'internal::SupportsOperation']]],
  ['dgp_5fdofs_5fper_5fcomponent_11706',['DGP_dofs_per_component',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component.html',1,'internal::MatrixFreeFunctions']]],
  ['dgp_5fdofs_5fper_5fcomponent_3c_201_2c_20degree_20_3e_11707',['DGP_dofs_per_component&lt; 1, degree &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component_3_011_00_01degree_01_4.html',1,'internal::MatrixFreeFunctions']]],
  ['diagonalmatrix_11708',['DiagonalMatrix',['http://www.dealii.org/developer/doxygen/deal.II/classDiagonalMatrix.html',1,'']]],
  ['dictionary_11709',['Dictionary',['http://www.dealii.org/developer/doxygen/deal.II/structUtilities_1_1MPI_1_1internal_1_1ComputeIndexOwner_1_1Dictionary.html',1,'Utilities::MPI::internal::ComputeIndexOwner']]],
  ['dictionaryoptimizer_11710',['DictionaryOptimizer',['http://www.dealii.org/developer/doxygen/deal.II/structDifferentiation_1_1SD_1_1internal_1_1DictionaryOptimizer.html',1,'Differentiation::SD::internal']]],
  ['dictionarypayload_11711',['DictionaryPayLoad',['http://www.dealii.org/developer/doxygen/deal.II/classUtilities_1_1MPI_1_1internal_1_1ComputeIndexOwner_1_1DictionaryPayLoad.html',1,'Utilities::MPI::internal::ComputeIndexOwner']]],
  ['dictionarysubstitutionvisitor_11712',['DictionarySubstitutionVisitor',['http://www.dealii.org/developer/doxygen/deal.II/classDifferentiation_1_1SD_1_1internal_1_1DictionarySubstitutionVisitor.html',1,'Differentiation::SD::internal']]],
  ['dimension_3c_3a_3apoint_3c_20dim_2c_20number_20_3e_20_3e_11713',['dimension&lt;::Point&lt; dim, Number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structboost_1_1geometry_1_1traits_1_1dimension_3_1_1Point_3_01dim_00_01Number_01_4_01_4.html',1,'boost::geometry::traits']]],
  ['directionalprojectionmanifold_11714',['DirectionalProjectionManifold',['http://www.dealii.org/developer/doxygen/deal.II/classOpenCASCADE_1_1DirectionalProjectionManifold.html',1,'OpenCASCADE']]],
  ['directoryname_11715',['DirectoryName',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1DirectoryName.html',1,'Patterns']]],
  ['discretefacequadraturegenerator_11716',['DiscreteFaceQuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1DiscreteFaceQuadratureGenerator.html',1,'NonMatching']]],
  ['discretelevelsetdescription_11717',['DiscreteLevelSetDescription',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1MeshClassifierImplementation_1_1DiscreteLevelSetDescription.html',1,'NonMatching::internal::MeshClassifierImplementation']]],
  ['discretequadraturegenerator_11718',['DiscreteQuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1DiscreteQuadratureGenerator.html',1,'NonMatching']]],
  ['discretetime_11719',['DiscreteTime',['http://www.dealii.org/developer/doxygen/deal.II/classDiscreteTime.html',1,'']]],
  ['distortedcelllist_11720',['DistortedCellList',['http://www.dealii.org/developer/doxygen/deal.II/structTriangulation_1_1DistortedCellList.html',1,'Triangulation']]],
  ['distributedcomputepointlocationsinternal_11721',['DistributedComputePointLocationsInternal',['http://www.dealii.org/developer/doxygen/deal.II/structGridTools_1_1internal_1_1DistributedComputePointLocationsInternal.html',1,'GridTools::internal']]],
  ['distributedlagrange_11722',['DistributedLagrange',['../class_p_d_es_1_1_distributed_lagrange.html',1,'PDEs']]],
  ['distributedtree_11723',['DistributedTree',['http://www.dealii.org/developer/doxygen/deal.II/classArborXWrappers_1_1DistributedTree.html',1,'ArborXWrappers']]],
  ['distributedtriangulationbase_11724',['DistributedTriangulationBase',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'parallel']]],
  ['distributedtriangulationbase_3c_201_2c_20spacedim_20_3e_11725',['DistributedTriangulationBase&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'']]],
  ['distributedtriangulationbase_3c_20dim_2c_20dim_20_3e_11726',['DistributedTriangulationBase&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'']]],
  ['dofaccessor_11727',['DoFAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofaccessor_3c_200_2c_201_2c_20spacedim_2c_20level_5fdof_5faccess_20_3e_11728',['DoFAccessor&lt; 0, 1, spacedim, level_dof_access &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor_3_010_00_011_00_01spacedim_00_01level__dof__access_01_4.html',1,'']]],
  ['dofaccessor_3c_20dimension_5f_2c_20dimension_5f_2c_20space_5fdimension_5f_2c_20level_5fdof_5faccess_20_3e_11729',['DoFAccessor&lt; dimension_, dimension_, space_dimension_, level_dof_access &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofcellaccessor_11730',['DoFCellAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFCellAccessor.html',1,'']]],
  ['doffaces_11731',['DoFFaces',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_201_20_3e_11732',['DoFFaces&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_011_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_202_20_3e_11733',['DoFFaces&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_012_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_203_20_3e_11734',['DoFFaces&lt; 3 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_013_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_20spacedim_20_3e_11735',['DoFFaces&lt; spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces.html',1,'internal::DoFHandlerImplementation']]],
  ['dofhandler_11736',['DoFHandler',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_201_2c_20spacedim_20_3e_11737',['DoFHandler&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_20_3e_11738',['DoFHandler&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_2c_20dim_20_3e_11739',['DoFHandler&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20patch_5fdim_2c_20spacedim_20_3e_11740',['DoFHandler&lt; patch_dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20spacedim_2c_20spacedim_20_3e_11741',['DoFHandler&lt; spacedim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofinfo_11742',['DoFInfo',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DoFInfo.html',1,'internal::MatrixFreeFunctions::DoFInfo'],['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1DoFInfo.html',1,'MeshWorker::DoFInfo&lt; dim, spacedim, number &gt;']]],
  ['dofinfobox_11743',['DoFInfoBox',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1DoFInfoBox.html',1,'MeshWorker']]],
  ['dofinvalidaccessor_11744',['DoFInvalidAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFInvalidAccessor.html',1,'']]],
  ['doflevel_11745',['DoFLevel',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFLevel.html',1,'internal::DoFHandlerImplementation']]],
  ['doflevel_3c_20spacedim_20_3e_11746',['DoFLevel&lt; spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFLevel.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_11747',['DoFObjects',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_3c_201_20_3e_11748',['DoFObjects&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation::DoFObjects&lt; 1 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'DoFObjects&lt; 1 &gt;']]],
  ['dofobjects_3c_202_20_3e_11749',['DoFObjects&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'DoFObjects&lt; 2 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation::DoFObjects&lt; 2 &gt;']]],
  ['dofobjects_3c_20spacedim_20_3e_11750',['DoFObjects&lt; spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofoutputoperator_11751',['DoFOutputOperator',['http://www.dealii.org/developer/doxygen/deal.II/classAlgorithms_1_1DoFOutputOperator.html',1,'Algorithms']]],
  ['dofpair_11752',['DoFPair',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MGTransfer_1_1DoFPair.html',1,'internal::MGTransfer']]],
  ['dofprintsolverstep_11753',['DoFPrintSolverStep',['http://www.dealii.org/developer/doxygen/deal.II/classDoFPrintSolverStep.html',1,'']]],
  ['dot_11754',['Dot',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1VectorOperations_1_1Dot.html',1,'internal::VectorOperations']]],
  ['dotproduct_11755',['DotProduct',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1DotProduct.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['double_11756',['Double',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1Double.html',1,'Patterns']]],
  ['double_5fcontraction_5fresult_11757',['double_contraction_result',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result.html',1,'internal::SymmetricTensorAccessors']]],
  ['double_5fcontraction_5fresult_3c_202_2c_202_2c_20dim_2c_20number_2c_20othernumber_20_3e_11758',['double_contraction_result&lt; 2, 2, dim, Number, OtherNumber &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result_3_012_00_012_00_01dim_bde24087db8a52ec06f500b41dd95304.html',1,'internal::SymmetricTensorAccessors']]],
  ['duplicatedcommunicator_11759',['DuplicatedCommunicator',['http://www.dealii.org/developer/doxygen/deal.II/classUtilities_1_1MPI_1_1DuplicatedCommunicator.html',1,'Utilities::MPI']]],
  ['dx_11760',['DX',['http://www.dealii.org/developer/doxygen/deal.II/structGridOutFlags_1_1DX.html',1,'GridOutFlags']]],
  ['dxflags_11761',['DXFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1DXFlags.html',1,'DataOutBase']]],
  ['dynamicsparsitypattern_11762',['DynamicSparsityPattern',['http://www.dealii.org/developer/doxygen/deal.II/classDynamicSparsityPattern.html',1,'']]]
];
