name: github-docker

on: 
  push: 
    branches: [main]

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image of master 
        uses: docker/build-push-action@v3
        with:
          context: ./docker/
          file: ./docker/Dockerfile.fsi-suite
          cache-from: type=registry,ref=heltai/dealii:vscode
          cache-to: type=inline
          push: true
          tags: heltai/fsi-suite:latest

