name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug:

    runs-on: ubuntu-latest
    container: 
      image: heltai/dealii:vscode
      options: --user root

    steps:
    - uses: actions/checkout@v2
    - name: Build debug
      run: |
         rm -rf build_linux_debug
         mkdir build_linux_debug 
         cd build_linux_debug
         cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
         ninja

    - name: CTest debug
      run: |
         cd build_linux_debug
         ctest -N
         ctest --output-on-failure

  release:

    runs-on: ubuntu-latest
    container: 
      image: heltai/dealii:vscode
      options: --user root

    steps:
    - uses: actions/checkout@v2
    - name: Build release
      run: |
          rm -rf build_linux_release
          mkdir build_linux_release
          cd build_linux_release
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
          ninja

    - name: CTest release
      run: |
         cd build_linux_release
         ctest -N
         ctest --output-on-failure
